services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432/yairacunadb?schema=public
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    restart: always
    container_name: postgres17
    environment:
      POSTGRES_DB: yairacunadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    # Local, erase if want to do all in docker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yairacunadb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
