import {
  SiReact,
  SiTailwindcss,
  SiNodedotjs,
  SiJavascript,
  SiCplusplus,
  SiPrisma,
  SiDocker,
  SiAstro,
  SiPython,
  SiPostgresql,
  SiFlask,
  SiTypescript,
  SiKotlin,
  SiCss3,
  SiPhp,
  SiAngular,
  SiMongodb,
  SiKubernetes,
  SiScala,
  SiGraphql,
  SiDjango,
  SiSwift,
  SiSymfony,
  SiExpress,
  SiDart,
  SiApollographql,
  SiElixir,
  SiAnsible,
  SiHaskell,
  SiRedis,
  SiTerraform,
} from "react-icons/si";
import {
  TbBrandCSharp,
  TbBrandLaravel,
  TbBrandNextjs,
  TbSql,
  TbBrandGolang,
} from "react-icons/tb";
import { GiCamel, GiSadCrab } from "react-icons/gi";
import { DiRuby } from "react-icons/di";
import { BiLogoSpringBoot, BiLogoVuejs } from "react-icons/bi";
import { RiJavaLine } from "react-icons/ri";
import { FaHtml5 } from "react-icons/fa";
import { GrMysql } from "react-icons/gr";

export const iconTechMap = {
  react: SiReact,
  tailwindcss: SiTailwindcss,
  nodejs: SiNodedotjs,
  javascript: SiJavascript,
  cplusplus: SiCplusplus,
  csharp: TbBrandCSharp,
  prisma: SiPrisma,
  nextjs: TbBrandNextjs,
  docker: SiDocker,
  astro: SiAstro,
  python: SiPython,
  postgres: SiPostgresql,
  flask: SiFlask,
  typescript: SiTypescript,
  kotlin: SiKotlin,
  css: SiCss3,
  perl: GiCamel,
  php: SiPhp,
  sql: TbSql,
  ruby: DiRuby,
  springboot: BiLogoSpringBoot,
  angular: SiAngular,
  laravel: TbBrandLaravel,
  mongodb: SiMongodb,
  kubernetes: SiKubernetes,
  scala: SiScala,
  golang: TbBrandGolang,
  graphql: SiGraphql,
  django: SiDjango,
  swift: SiSwift,
  symfony: SiSymfony,
  expressjs: SiExpress,
  rust: GiSadCrab,
  dart: SiDart,
  apollo: SiApollographql,
  java: RiJavaLine,
  elixir: SiElixir,
  ansible: SiAnsible,
  html: FaHtml5,
  mysql: GrMysql,
  vuejs: BiLogoVuejs,
  haskell: SiHaskell,
  redis: SiRedis,
  terraform: SiTerraform,
};
